### ISSUE TITLE
Malaysian Number plate

### ISSUE THREAD

**Issue by zulhilmyamy** [theAIGuysCode/yolov4-custom-functions#26]
Hye, i tried the code it's work, but when using Malaysian number plate, the program detect the plate but cant return the plate number. Anybody had any idea with that ?

![8](https://user-images.githubusercontent.com/74761564/101439313-3a679a80-394f-11eb-9642-f4532c286b95.png)

![9](https://user-images.githubusercontent.com/74761564/101439335-44899900-394f-11eb-94f5-c1627ec45b32.png)

**Comment by mahamatnoumai** [comment]
try to use [regex](https://docs.python.org/3/library/re.html) to struct the plate number on that specific bounding box. bc Malaysian plate number has different way to extract it. 

u can change the code from here: 
https://github.com/theAIGuysCode/yolov4-custom-functions/blob/8f2c922a54d9ee0878efd3dffa42ce6e7bd3ae34/core/utils.py#L78
