### ISSUE TITLE
Streaming videos from an IP.

### ISSUE THREAD

**Issue by Samar-080301** [theAIGuysCode/yolov4-custom-functions#6]
I wanted to use my phone camera for streaming the video for detections. So I got an app called IP webcam where it sent live camera display to my pc via an IP like `https://192.168.0.0.1/camera`, it's just a demo.
 So how can I use this video in the model?

**Comment by jmudy** [comment]
You can use IP webcam using the following:

`python detect_video.py --weights ./checkpoints/yolov4-416 --size 416 --model yolov4 --video http://192.168.0.80:8080/video?dummy=param.mjpg`

You just have to change the IP you get when you start the server in IP Webcam

**Comment by Samar-080301** [comment]
Thanks a lot for your help!! Project is great motivation for DL beginners.
