### ISSUE TITLE
cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

### ISSUE THREAD

**Issue by Ghada-Ch** [theAIGuysCode/yolov4-custom-functions#96]
Hello, It didn't work for me , I always get this Error
 gray = cv2.cvtColor(box, cv2.COLOR_RGB2GRAY)
cv2.error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

I verified the img if it is empty :+1: 
cv2.imshow("img", img)
But it isn't.
Any idea ?
Thanks

**Comment by isinsuarici** [comment]
What is your tensorflow version?

**Comment by HamidFsian** [comment]
Hello,
Maybe you should check if the image you're giving is indeed in RGB. Because when doing an imread using opencv you will have the image in BRG format. 
So make sure which representation you are using.
